import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, MapPin } from 'lucide-react';
import { Skeleton } from '@/components/ui/skeleton';
import { useFundraisers, type Fundraiser } from '@/hooks/useFundraisers';
import { FundraiserFilterBar, type FundraiserFilters } from '@/components/stories/FundraiserFilterBar';
import { useZipStates } from '@/lib/zipStates';
import { ImageReveal, LineReveal, MotionBar, Reveal } from '@/components/ui/editorial-motion';

const imageFor=(f:Fundraiser)=>f.fundraiser_images?.find(i=>i.is_primary)?.image_url||f.fundraiser_images?.[0]?.image_url||f.cover_photo_url;
const pct=(f:Fundraiser)=>f.monthly_goal>0?Math.min((f.amount_raised/f.monthly_goal)*100,100):0;
function StoryTile({fundraiser,lead=false}:{fundraiser:Fundraiser;lead?:boolean}){const image=imageFor(fundraiser);return <Link to={`/f/${fundraiser.unique_slug}`} className="group block snap-start"><article className="h-full overflow-hidden rounded-[1.5rem] bg-background transition-transform duration-500 hover:-translate-y-1">{image?<ImageReveal className={lead?'aspect-[16/10]':'aspect-[4/3]'}><img src={image} alt={fundraiser.title} className="h-full w-full object-contain transition-transform duration-700 group-hover:scale-[1.04]" loading="lazy" sizes={lead?'(min-width: 768px) 62vw, 88vw':'(min-width: 768px) 32vw, 88vw'}/></ImageReveal>:<div className={lead?'aspect-[16/10] bg-primary/10':'aspect-[4/3] bg-primary/10'}/>}<div className={lead?'p-7 md:p-9':'p-6'}><p className="flex items-center gap-2 text-sm text-muted-foreground"><MapPin className="h-4 w-4"/>{fundraiser.country||'United States'}</p><h3 className={`${lead?'text-4xl md:text-5xl':'text-3xl'} mt-3 font-display font-normal leading-tight text-foreground`}>{fundraiser.title}</h3><p className="mt-3 line-clamp-2 leading-relaxed text-muted-foreground">{fundraiser.story}</p><div className="mt-6 h-2 overflow-hidden rounded-full bg-primary/10"><MotionBar value={pct(fundraiser)} className="h-full w-full rounded-full bg-primary"/></div><div className="mt-3 flex justify-between text-sm"><strong className="text-foreground">${fundraiser.amount_raised.toLocaleString()}</strong><span className="text-muted-foreground">${fundraiser.monthly_goal.toLocaleString()} goal</span></div><span className="mt-6 inline-flex items-center text-sm font-semibold text-primary">View fundraiser <ArrowRight className="ml-2 h-4 w-4"/></span></div></article></Link>}
export function ImpactStories(){const[filters,setFilters]=useState<FundraiserFilters>({category:'all',state:'all'});const{data,isLoading}=useFundraisers({limit:24});const stateMap=useZipStates(data||[]);const filtered=useMemo(()=>(data||[]).filter(f=>(filters.category==='all'||f.category===filters.category)&&(filters.state==='all'||(f.zip_code&&stateMap.get(f.zip_code)===filters.state))),[data,filters,stateMap]);if(isLoading)return <section className="bg-background py-24"><div className="container mx-auto grid gap-6 px-4 md:grid-cols-2"><Skeleton className="aspect-[16/10] rounded-[1.5rem]"/><Skeleton className="aspect-[4/3] rounded-[1.5rem]"/></div></section>;if(!data?.length)return null;return <section className="bg-background py-24 md:py-36"><div className="container mx-auto px-4"><div className="mb-12 grid gap-6 md:grid-cols-[1.2fr_.8fr] md:items-end"><LineReveal><h2 className="font-display text-5xl font-normal leading-none text-foreground md:text-7xl">Meet the people asking for help.</h2></LineReveal><Reveal delay={.1}><p className="text-lg leading-relaxed text-muted-foreground">Every total below comes from an active fundraiser record.</p></Reveal></div><FundraiserFilterBar filters={filters} onChange={setFilters}/>{filtered.length?<div className="mt-8 flex snap-x gap-5 overflow-x-auto pb-5 md:grid md:grid-cols-[1.65fr_1fr] md:overflow-visible"><div className="w-[88vw] shrink-0 md:w-auto"><StoryTile fundraiser={filtered[0]} lead/></div><div className="flex w-[88vw] shrink-0 flex-col gap-5 md:w-auto">{filtered.slice(1,3).map(f=><StoryTile key={f.id} fundraiser={f}/>)}</div></div>:<div className="mt-8 rounded-[1.5rem] bg-secondary p-10 text-muted-foreground">No fundraisers match these filters yet.</div>}<Link to="/stories" className="mt-8 inline-flex items-center font-semibold text-primary">View all fundraisers <ArrowRight className="ml-2 h-4 w-4"/></Link></div></section>}