import { CheckCircle, Heart, PieChart, ShoppingCart, Users } from 'lucide-react';
import { motion, useInView } from 'motion/react';
import { useRef } from 'react';
import { LineReveal, Reveal, MotionBar } from '@/components/ui/editorial-motion';
import { useMotionPreference } from '@/hooks/useMotionPreference';

const breakdown=[{label:'Direct to Recipients',percent:95,Icon:Heart},{label:'Platform Operations',percent:3,Icon:PieChart},{label:'Payment Processing',percent:2,Icon:CheckCircle}];
const journey=[{title:'You Donate',text:'Choose a brand and amount',Icon:Heart},{title:'We Purchase',text:'Buy coupons at wholesale',Icon:ShoppingCart},{title:'Families Receive',text:'Direct distribution',Icon:Users},{title:'Impact Verified',text:'Transparent tracking',Icon:CheckCircle}];
function Ring(){const ref=useRef<HTMLDivElement>(null);const seen=useInView(ref,{once:true,amount:.5});const pref=useMotionPreference();const c=2*Math.PI*82;return <div ref={ref} className="relative mx-auto h-64 w-64"><svg viewBox="0 0 200 200" className="h-full w-full -rotate-90"><circle cx="100" cy="100" r="82" fill="none" stroke="hsl(var(--primary-foreground)/.14)" strokeWidth="16"/><motion.circle cx="100" cy="100" r="82" fill="none" stroke="hsl(var(--primary-foreground))" strokeWidth="16" strokeLinecap="round" strokeDasharray={c} initial={{strokeDashoffset:c}} animate={seen?{strokeDashoffset:c*.05}:undefined} transition={{duration:pref==='full'?1.6:.7,ease:[.16,1,.3,1]}}/></svg><div className="absolute inset-0 flex flex-col items-center justify-center"><strong className="font-display text-7xl font-normal text-primary-foreground">95¢</strong><span className="text-sm text-primary-foreground/70">of every $1</span></div></div>}
export function TrustTransparency(){return <section className="bg-[hsl(var(--primary-20))] py-24 text-primary-foreground md:py-36"><div className="container mx-auto px-4"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><Reveal><Ring/></Reveal><div><LineReveal><h2 className="font-display text-5xl font-normal leading-none md:text-7xl">See where every dollar goes.</h2></LineReveal><Reveal delay={.1}><p className="mt-6 max-w-xl text-lg leading-relaxed text-primary-foreground/75">The allocation and coupon trail stay visible, from donation to use.</p></Reveal><div className="mt-10 space-y-6">{breakdown.map((item,i)=><Reveal key={item.label} delay={i*.09}><div className="flex items-end justify-between gap-4"><span className="flex items-center gap-3"><item.Icon className="h-5 w-5"/>{item.label}</span><strong className="font-display text-4xl font-normal">{item.percent}%</strong></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-primary-foreground/15"><MotionBar value={item.percent} className="h-full w-full rounded-full bg-primary-foreground"/></div></Reveal>)}</div></div></div><div className="relative mt-20 grid gap-8 md:grid-cols-4"><motion.div className="absolute left-0 right-0 top-5 hidden h-px origin-left bg-primary-foreground/35 md:block" initial={{scaleX:0}} whileInView={{scaleX:1}} viewport={{once:true,amount:.6}} transition={{duration:1.5,ease:[.16,1,.3,1]}}/>{journey.map((item,i)=><Reveal key={item.title} delay={i*.09} className="relative"><div className="mb-7 flex h-10 w-10 items-center justify-center rounded-full bg-primary-foreground text-[hsl(var(--primary-20))]"><item.Icon className="h-5 w-5"/></div><span className="text-sm text-primary-foreground/60">0{i+1}</span><h3 className="mt-2 font-display text-3xl font-normal">{item.title}</h3><p className="mt-2 text-primary-foreground/70">{item.text}</p></Reveal>)}</div><Reveal className="mt-16 rounded-[1.5rem] bg-primary-foreground/10 p-7 text-center"><p><strong>95¢ of every dollar</strong> goes directly to purchasing coupons for families in need.</p></Reveal></div></section>}