import { Link } from 'react-router-dom';
import { ArrowRight, Calendar } from 'lucide-react';
import { format, parseISO } from 'date-fns';
import { SEO, breadcrumbJsonLd } from '@/components/SEO';
import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/layout/Footer';
import { Skeleton } from '@/components/ui/skeleton';
import { ImageReveal, LineReveal, Reveal } from '@/components/ui/editorial-motion';
import { useCMSPosts } from '@/hooks/useCMSContent';

export default function Blog(){
 const {data:posts,isLoading}=useCMSPosts(true);
 return <div className="min-h-dvh bg-background"><SEO title="Blog & Updates" description="News, product updates, and perspectives from CouponDonation." path="/blog" jsonLd={breadcrumbJsonLd([{name:'Home',path:'/'},{name:'Blog',path:'/blog'}])}/><Navbar/><main><section className="py-24 md:py-36"><div className="container mx-auto px-4"><LineReveal><h1 className="max-w-4xl font-display text-6xl font-normal leading-none text-foreground md:text-8xl">Notes on clearer giving.</h1></LineReveal><Reveal delay={.1}><p className="mt-8 max-w-2xl text-xl leading-relaxed text-muted-foreground">Updates, ideas, and practical context from the CouponDonation team.</p></Reveal></div></section><section className="py-20 md:py-28" style={{backgroundColor:'hsl(var(--primary-97))'}}><div className="container mx-auto max-w-6xl px-4">{isLoading?<div className="grid gap-10 md:grid-cols-2">{[1,2,3,4].map(i=><div key={i}><Skeleton className="aspect-[16/10] w-full"/><Skeleton className="mt-5 h-8 w-3/4"/><Skeleton className="mt-3 h-4 w-full"/></div>)}</div>:!posts?.length?<div className="border-y border-border py-16"><h2 className="font-display text-4xl text-foreground">The journal is quiet for now.</h2><p className="mt-3 text-muted-foreground">Published articles will appear here.</p></div>:<div className="grid gap-x-8 gap-y-16 md:grid-cols-2">{posts.map((post:any,index:number)=><Reveal key={post.id} delay={index*.05}><Link to={`/blog/${post.slug}`} className="group block">{post.cover_image_url&&<ImageReveal className="aspect-[16/10] bg-muted"><img src={post.cover_image_url} alt={post.title} className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-[1.02]"/></ImageReveal>}<div className="pt-5"><div className="flex items-center gap-3 text-sm text-muted-foreground"><span>{post.category}</span><span className="flex items-center gap-1"><Calendar className="h-4 w-4"/>{format(parseISO(post.published_at||post.created_at),'MMM d, yyyy')}</span></div><h2 className="mt-3 font-display text-4xl font-normal leading-tight text-foreground">{post.title}</h2><p className="mt-3 line-clamp-3 leading-relaxed text-muted-foreground">{post.excerpt||post.content.substring(0,180)}</p><span className="mt-5 inline-flex items-center text-sm font-medium text-primary">Read article <ArrowRight className="ml-2 h-4 w-4"/></span></div></Link></Reveal>)}</div>}</div></section></main><Footer/></div>
}