import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, Calendar } from 'lucide-react';
import { format, parseISO } from 'date-fns';
import { SEO, breadcrumbJsonLd } from '@/components/SEO';
import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/layout/Footer';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { ImageReveal, LineReveal, Reveal } from '@/components/ui/editorial-motion';
import { useCMSPost } from '@/hooks/useCMSContent';

export default function BlogPost(){
 const {slug}=useParams<{slug:string}>(); const {data:post,isLoading}=useCMSPost(slug||'');
 return <div className="min-h-dvh bg-background">{post&&<SEO title={post.title} description={(post.excerpt||post.title).slice(0,155)} path={`/blog/${slug}`} type="article" image={post.cover_image_url||undefined} jsonLd={breadcrumbJsonLd([{name:'Home',path:'/'},{name:'Blog',path:'/blog'},{name:post.title,path:`/blog/${slug}`}])}/>}<Navbar/><main className="py-16 md:py-24" style={{backgroundColor:'hsl(var(--primary-97))'}}><div className="container mx-auto max-w-5xl px-4"><Button variant="ghost" asChild className="mb-10"><Link to="/blog"><ArrowLeft className="mr-2 h-4 w-4"/>Back to journal</Link></Button>{isLoading?<div className="space-y-5"><Skeleton className="h-16 w-4/5"/><Skeleton className="h-5 w-1/3"/><Skeleton className="aspect-[16/9] w-full"/></div>:!post?<div className="border-y border-border py-16"><h1 className="font-display text-5xl text-foreground">Article not found.</h1><Button asChild className="mt-7"><Link to="/blog">Browse articles</Link></Button></div>:<article><header className="max-w-4xl"><Reveal><div className="flex items-center gap-3 text-sm text-muted-foreground"><span>{post.category}</span><span className="flex items-center gap-1"><Calendar className="h-4 w-4"/>{format(parseISO(post.published_at||post.created_at),'MMMM d, yyyy')}</span></div></Reveal><LineReveal><h1 className="mt-5 font-display text-6xl font-normal leading-none text-foreground md:text-8xl">{post.title}</h1></LineReveal>{post.excerpt&&<Reveal delay={.08}><p className="mt-7 max-w-3xl text-xl leading-relaxed text-muted-foreground">{post.excerpt}</p></Reveal>}</header>{post.cover_image_url&&<ImageReveal className="mt-12 aspect-[16/9] bg-muted"><img src={post.cover_image_url} alt={post.title} className="h-full w-full object-cover"/></ImageReveal>}<Reveal><div className="mx-auto mt-14 max-w-3xl">{post.content.split('\n').map((paragraph:string,index:number)=>paragraph.trim()?<p key={index} className="mb-6 text-lg leading-8 text-foreground/90">{paragraph}</p>:null)}{post.tags?.length>0&&<div className="mt-12 flex flex-wrap gap-x-5 gap-y-2 border-t border-border pt-7 text-sm text-muted-foreground">{post.tags.map((tag:string)=><span key={tag}>{tag}</span>)}</div>}</div></Reveal></article>}</div></main><Footer/></div>
}