INSERT INTO cms_stories (name, location, category, short_story, full_story, goal, amount_raised, donors_count, impact, image_url, is_published, display_order)
VALUES (
  'Grace N.',
  'Kampala, Uganda',
  'children',
  'When I lost my teaching job during the school closures, my three children went from eating two meals a day to barely one. CouponDonation''s grocery coupons carried us through six months until I found work again. Now my children are back in school and thriving.',
  E'I was a primary school teacher for eight years in Kampala. Teaching was not just my job — it was my calling. When the school closures came, everything changed overnight. The small private school where I worked couldn''t pay salaries anymore, and just like that, I was unemployed.\n\nMy three children — Faith (10), David (7), and baby Sarah (3) — depended entirely on me. Their father left us years ago, and I had no family nearby to lean on. Within two weeks, we went from two modest meals a day to barely one. I would skip eating entirely so my children could have something.\n\nThe hardest moment was when Faith came home from a neighbor''s house and told me, "Mama, they had rice and beans. Can we have that too?" I had nothing in the kitchen. I cried that night after the children fell asleep.\n\nA woman at my church told me about CouponDonation. She had received grocery coupons herself and said the process was simple. I was hesitant — I had always been the one helping others, not asking for help. But my children''s hunger pushed me past my pride.\n\nI applied on a Sunday evening. By Wednesday, I had my first set of grocery coupons for a local market in Kampala. I remember walking through the aisles with Faith, filling our basket with maize flour, beans, cooking oil, and vegetables. Faith looked up at me and said, "Mama, we''re going to eat today!" That simple sentence broke and healed my heart at the same time.\n\nFor six months, CouponDonation provided consistent grocery support. Every two weeks, new coupons arrived. The reliability was what mattered most — I could plan meals, I could focus on finding work instead of panicking about dinner.\n\nDuring those six months, I heard about a teaching position at a community school in a neighboring district. It paid less than my old job, but it was steady work. I applied, interviewed, and got the position. My first paycheck felt like the greatest achievement of my life.\n\nToday, all three of my children are back in school. Faith is top of her class. David has discovered a love for drawing. And baby Sarah is the happiest three-year-old you''ll ever meet. I now volunteer two evenings a week at my church, helping other families navigate the CouponDonation application process.\n\nTo every person who donated: you fed my children when I couldn''t. You gave me the breathing room to find my feet again. You didn''t just provide groceries — you restored a mother''s dignity and gave three children their childhood back. Thank you, from the bottom of my heart.',
  3000,
  2340,
  312,
  '6 months of groceries for a family of 4',
  'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&h=600&fit=crop',
  true,
  2
);