-- Update existing 4 stories with image URLs
UPDATE cms_stories SET image_url = '/featured/childrens-hope.webp' WHERE name = 'Children''s Hope Program';
UPDATE cms_stories SET image_url = '/featured/rural-family-support.webp' WHERE name = 'Rural Family Support';
UPDATE cms_stories SET image_url = '/featured/hurricane-relief.webp' WHERE name = 'Hurricane Helene Relief';
UPDATE cms_stories SET image_url = '/featured/children-of-heroes.jpeg' WHERE name = 'Children of Heroes';

-- Insert 4 new stories for unused images
INSERT INTO cms_stories (name, location, category, short_story, full_story, amount_raised, goal, donors_count, is_published, display_order, image_url)
VALUES
('Children at Play', 'Poland', 'child', 'In Poland, displaced children are rediscovering joy through organized play programs that provide safe spaces, creative activities, and peer connections during uncertain times.', 'In Poland, displaced children are rediscovering joy through organized play programs that provide safe spaces, creative activities, and peer connections during uncertain times. These programs offer structured recreation, art therapy, and language classes that help children process trauma while building friendships across cultures.', 9200, 14000, 156, true, 16, '/featured/children-playing-hope.webp'),
('Heroes'' Legacy: Next Generation', 'Ukraine', 'child', 'The next generation of Ukrainian children whose parents made the ultimate sacrifice are being supported with education, nutrition, and mentorship programs.', 'The next generation of Ukrainian children whose parents made the ultimate sacrifice are being supported with education, nutrition, and mentorship programs. Community volunteers and international donors have come together to ensure these children have access to quality schooling, balanced meals, and caring adults who guide them through their formative years.', 14500, 22000, 198, true, 17, '/featured/children-of-heroes-2.jpeg'),
('Life in Rural Haiti', 'Haiti', 'family', 'Families in remote Haitian villages are gaining access to clean water, food supplies, and agricultural training that transforms their daily lives.', 'Families in remote Haitian villages are gaining access to clean water, food supplies, and agricultural training that transforms their daily lives. With donor support, communities are building sustainable irrigation systems, establishing seed banks, and training local farmers in climate-resilient techniques that ensure long-term food security.', 7800, 12000, 112, true, 18, '/featured/haiti-rural-family.webp'),
('Hurricane Helene: Family Recovery', 'North Carolina, USA', 'emergency', 'Families devastated by Hurricane Helene in North Carolina are rebuilding their lives with emergency shelter, food assistance, and community support.', 'Families devastated by Hurricane Helene in North Carolina are rebuilding their lives with emergency shelter, food assistance, and community support. When the storm swept through mountain communities, it destroyed homes, roads, and livelihoods overnight. Donors stepped in immediately with temporary housing, hot meals, and supplies to help families begin the long road to recovery.', 18900, 30000, 267, true, 19, '/featured/hurricane-helene-family.webp');