
-- Seed cms_stories with hardcoded impact stories
INSERT INTO cms_stories (name, location, image_url, short_story, full_story, impact, category, donors_count, amount_raised, goal, is_published, display_order) VALUES
('Maria R.', 'Houston, TX', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face', 'After losing my job, I struggled to feed my three children. The grocery coupons from CouponDonation helped us get through the hardest months. Now I''m back on my feet and paying it forward.', 'When I lost my job at the manufacturing plant in March, I never imagined how quickly things would spiral. With three children to feed and rent coming due, I felt completely overwhelmed. My youngest daughter had just started kindergarten, and I couldn''t bear the thought of her going to school hungry. A friend from church told me about CouponDonation. The coupons didn''t just provide food. They gave me dignity. Three months later, I found a new job. The first thing I did was set up a monthly donation to CouponDonation.', '3 months of groceries', 'family', 234, 1850, 2000, true, 1),
('The Martinez Family', 'Phoenix, AZ', 'https://images.unsplash.com/photo-1609220136736-443140cffec6?w=400&h=400&fit=crop', 'When my husband was hospitalized, medical bills piled up. Thanks to generous donors, we received food delivery coupons that kept our family fed while we focused on his recovery.', 'Life can change in an instant. One day, my husband Carlos was working his construction job like any other day. The next, he was in the ICU with a serious injury. A social worker at the hospital mentioned CouponDonation. Within days, we received DoorDash and Instacart coupons. Carlos is recovering now. The food coupons meant I could focus on being by his side instead of worrying about whether our kids were eating properly.', '500+ meals delivered', 'emergency', 412, 3200, 3500, true, 2),
('David & Kids', 'Chicago, IL', 'https://images.unsplash.com/photo-1596464716127-f2a82984de30?w=400&h=400&fit=crop', 'As a single dad working two jobs, I couldn''t always provide healthy meals. The Walmart and Target coupons meant my kids could have fresh fruits and vegetables every week.', 'Being a single dad wasn''t in my life plan. When my wife passed away two years ago, I was left to raise our three kids on my own. When CouponDonation started sending us weekly grocery coupons, everything changed. My kids'' health improved. Their grades improved. And I finally felt like I was doing right by them.', 'Weekly groceries for 6 months', 'child', 189, 2400, 2400, true, 3),
('Hope Community Center', 'Atlanta, GA', 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=400&h=400&fit=crop', 'Our food bank serves 200 families weekly. Partner brand coupons have allowed us to provide not just food, but dignity - families can choose what they need.', 'Hope Community Center has been serving Atlanta''s underserved neighborhoods for over 15 years. CouponDonation changed our model completely. Now, instead of handing out random food items, we distribute coupons from partner retailers. We''ve seen a 40% increase in the number of families we can help since partnering with CouponDonation.', '200 families served weekly', 'community', 567, 8500, 10000, true, 4),
('Sarah T.', 'Denver, CO', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=face', 'After fleeing domestic violence, I had nothing. The clothing and grocery coupons helped me rebuild my life and regain my independence. Forever grateful.', 'I left with nothing but the clothes on my back and my two children. CouponDonation provided us with coupons for groceries, clothing, and household essentials. Six months later, I have my own apartment, a job, and most importantly, my freedom.', 'Fresh start package', 'emergency', 156, 1200, 1500, true, 5),
('James & Family', 'Seattle, WA', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face', 'When I was laid off during the holidays, feeding four kids seemed impossible. The holiday meal coupons meant we could still have a proper Christmas dinner together.', 'Tech layoffs hit Seattle hard in 2025. With four kids ranging from 6 to 16, the timing couldn''t have been worse. CouponDonation provided us with holiday meal coupons – enough for both Thanksgiving and Christmas dinners.', 'Holiday meals for 4 kids', 'family', 298, 1650, 1800, true, 6),
('Sunshine After School', 'Miami, FL', 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=400&h=400&fit=crop', 'We run an after-school program for 50 underprivileged children. The snack and meal coupons ensure no child goes hungry while learning and growing with us.', 'Sunshine After School started in my living room five years ago with just three kids. Today, we serve 50 children from low-income families in Miami''s Little Haiti neighborhood. With weekly grocery coupons, we can plan proper menus with fresh fruits, vegetables, lean proteins, and whole grains.', '50 children fed daily', 'child', 423, 4200, 5000, true, 7),
('Rosa M.', 'San Antonio, TX', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop&crop=face', 'As an elderly widow on fixed income, choosing between medicine and food was my reality. These coupons lifted that burden and gave me peace of mind.', 'I turned 78 this year. My Social Security check barely covers my rent and utilities. CouponDonation coupons meant I could afford both food AND medicine. My health has stabilized and I no longer lie awake at night wondering how I''ll survive the month.', '6 months of groceries', 'family', 187, 2100, 2100, true, 8);

-- Seed cms_testimonials with hardcoded testimonials
INSERT INTO cms_testimonials (quote, name, role, role_label, location, image_url, verified, is_published, display_order) VALUES
('I''ve donated to many platforms, but this is the first time I can see exactly where my money goes. Knowing my $50 became 100 meals for a family in need is incredibly fulfilling.', 'Sarah Chen', 'donor', 'Verified Donor', 'San Francisco, CA', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face', true, true, 1),
('When my family was struggling, these coupons helped us get essentials with dignity. I didn''t have to stand in a food line - I could shop like everyone else.', 'Maria G.', 'recipient', 'Verified Recipient', 'Houston, TX', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face', true, true, 2),
('As a DoorDash restaurant partner, we love that donations through our platform help feed families while supporting local businesses. It''s a win-win-win.', 'James Wilson', 'partner', 'Partner - DoorDash', 'New York, NY', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face', true, true, 3),
('I set up a monthly donation and receive updates showing exactly which families benefited. The transparency is what keeps me giving.', 'Michael Torres', 'donor', 'Monthly Donor', 'Austin, TX', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face', true, true, 4);

-- Seed cms_faq with hardcoded FAQ items
INSERT INTO cms_faq (question, answer, category, is_published, display_order) VALUES
('How does CouponDonation work?', 'CouponDonation connects donors who want to help with verified recipients in need. Donors contribute funds that are converted into coupons for essential goods. Recipients browse available coupons and redeem them at partner stores.', 'general', true, 1),
('How are recipients verified?', 'Recipients go through a multi-step verification process that includes income documentation, government ID verification, and optionally, referrals from partner organizations. This ensures donations reach those who truly need them.', 'general', true, 2),
('What categories of coupons are available?', 'We offer coupons across essential categories including Food & Groceries, Healthcare, Education, Clothing, Transportation, and Utilities. Donors can choose to support specific categories.', 'general', true, 3),
('How do I know my donation is making an impact?', 'Donors have access to a detailed impact dashboard showing exactly how their contributions are being used, including the number of families helped, categories supported, and geographic distribution.', 'general', true, 4),
('Is my personal information secure?', 'Absolutely. We use bank-level encryption and never share personal information. Recipient identities are protected - donors see impact metrics without personal details.', 'general', true, 5),
('Can I donate to specific regions or causes?', 'Yes! When making a donation, you can allocate your contribution to specific categories (like healthcare or education) or regions. You can also let us distribute where needs are greatest.', 'general', true, 6),
('How long does recipient verification take?', 'Most verifications are completed within 2-3 business days. You''ll receive email updates throughout the process, and you can track your application status in your dashboard.', 'general', true, 7),
('What is the loyalty card program?', 'Verified recipients receive a digital loyalty card. Each coupon redemption earns points that unlock additional benefits and shows their savings history. It''s our way of recognizing the journey to financial independence.', 'general', true, 8);
